version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Bruno123
      MYSQL_DATABASE: registro_db
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: MultipleFiles/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: Bruno
      DB_PASSWORD: Bruno123
      DB_NAME: registro_db
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  db_data: